export const ActionTypes = {
	SET_FEEDBACK: 'SET_FEEDBACK',
	SELECTED_FEEDBACK: 'SELECTED_FEEDBACK',
	EDIT_SELECTED_FEEDBACK: 'EDIT_SELECTED_FEEDBACK',
	REMOVE_SELECTED_FEEDBACK: 'REMOVE_SELECTED_FEEDBACK',
};
